spring:
  datasource:
    url: jdbc:mysql://${zh.datasource.ip}:3306/sunny?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${zh.datasource.username}
    password: ${zh.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.business.file.model
  global-config:
    db-config:
      id-type: INPUT

zh:
  file-server:
    type: fastdfs
    fdfs:
      web-url: ${zh.fdfs.web-url}
    #oss配置
    #oss:
    #  access-key: tpi8mObnfzZi4ggBX8Bw7zydjoTQ0WeML3RkPKsX
    #  accessKeySecret: HZBXmSyUTy-haYp0KbBTtsil-GoKjVS2kDKT8Yow
    #  endpoint: http://pkqtmn0p1.bkt.clouddn.com
    #  bucketName: public-oss
    #  domain:
  swagger:
    enabled: true
    title: 文件中心
    description: 文件中心接口文档
    version: 1.0
    base-package: com.business.file.controller

#fastDFS配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: ${zh.fdfs.trackerList}